name: Build

on:
  push:
    branches: [ "main", "rewrite" ]
  pull_request:
    branches: [ "main", "rewrite" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # time to try myself
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up devkitPro
        run: |
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman

      - name: Build Project
        run: |
          cd 3dscheck
          make  # hopefully this just works?
